/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const requests_Before_Create_Logic = require('./code/requests-before-create-logic');
const requests_Drafts_Before_Create_Logic = require('./code/requests-drafts-before-create-logic');
const requestitems_Drafts_Before_Create_Logic = require('./code/requestitems-drafts-before-create-logic');
const requests_After_Create_Logic = require('./code/requests-after-create-logic');
const requests_CalculateValues_Logic = require('./code/requests-calculateValues-logic');
const requests_Drafts_CalculateValues_Logic = require('./code/requests-drafts-calculateValues-logic');
const requests_After_Read_Logic = require('./code/requests-after-read-logic');
const downloaditemstemplate_Logic = require('./code/downloaditemstemplate-logic');
const requests_Drafts_Upload_Items_Logic = require('./code/requests-drafts-upload-items-logic');
const requestitems_Drafts_Before_Delete_Logic = require('./code/requestitems-drafts-before-delete-logic');
const requestitems_Drafts_After_Create_Logic = require('./code/requestitems-drafts-after-create-logic');
const requests_Before_Update_Logic = require('./code/requests-before-update-logic');

class ZSVC_PPS_VIREMENT extends LCAPApplicationService {
    async init() {

        this.before('CREATE', 'Requests', async (request) => {
            await requests_Before_Create_Logic(request);
        });

        this.before('CREATE', 'Requests.drafts', async (request) => {
            await requests_Drafts_Before_Create_Logic(request);
        });

        this.before('CREATE', 'RequestItems.drafts', async (request) => {
            await requestitems_Drafts_Before_Create_Logic(request);
        });

        this.after('CREATE', 'Requests', async (results, request) => {
            await requests_After_Create_Logic(results, request);
        });

        this.on('calculateValues', 'Requests', async (request) => {
            return requests_CalculateValues_Logic(request);
        });

        this.on('calculateValues', 'Requests.drafts', async (request) => {
            return requests_Drafts_CalculateValues_Logic(request);
        });

        this.after('READ', 'Requests', async (results, request) => {
            await requests_After_Read_Logic(results, request);
        });

        this.on('downloadItemsTemplate', async (request) => {
            return downloaditemstemplate_Logic(request);
        });

        this.on('uploadItems', 'Requests.drafts', async (request) => {
            return requests_Drafts_Upload_Items_Logic(request);
        });

        this.before('DELETE', 'RequestItems.drafts', async (request) => {
            await requestitems_Drafts_Before_Delete_Logic(request);
        });

        this.after('CREATE', 'RequestItems.drafts', async (results, request) => {
            await requestitems_Drafts_After_Create_Logic(results, request);
        });

        this.before('UPDATE', 'Requests', async (request) => {
            await requests_Before_Update_Logic(request);
        });

        return super.init();
    }
}


module.exports = {
    ZSVC_PPS_VIREMENT
};