/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require("@sap/low-code-event-handler");
const requests_Before_Create_Logic = require("./code/requests-before-create-logic");
const requests_Drafts_Before_Create_Logic = require("./code/requests-drafts-before-create-logic");
const requestitems_Drafts_Before_Create_Logic = require("./code/requestitems-drafts-before-create-logic");
const requestitems_Drafts_Before_Update_Logic = require("./code/requestitems-drafts-before-update-logic");
const requests_After_Create_Logic = require("./code/requests-after-create-logic");
const requests_CalculateValues_Logic = require("./code/requests-calculateValues-logic");
const requests_Drafts_CalculateValues_Logic = require("./code/requests-drafts-calculateValues-logic");
const requests_After_Read_Logic = require("./code/requests-after-read-logic");
const download_Items_Template_Logic = require("./code/download-items-template-logic");
const requests_Drafts_Upload_Items_Logic = require("./code/requests-drafts-upload-items-logic");
const requestitems_Drafts_Before_Delete_Logic = require("./code/requestitems-drafts-before-delete-logic");
const requestitems_Drafts_After_Create_Logic = require("./code/requestitems-drafts-after-create-logic");
const requestitems_Drafts_After_Update_Logic = require("./code/requestitems-drafts-after-update-logic");
const requests_Before_Update_Logic = require("./code/requests-before-update-logic");
const requests_Drafts_After_Read_Logic = require("./code/requests-drafts-after-read-logic");
const requests_Drafts_After_Update_Logic = require("./code/requests-drafts-after-update-logic");
const recent_Requests_Read_Logic = require("./code/recent-requests-read-logic");
const user_Details_Read_Logic = require("./code/user-details-read-logic");
const pending_Approval_Count_Read_Logic = require("./code/pending-approval-count-read-logic");
const requests_List_Scope_Logic = require("./code/requests-list-scope-logic");
const cost_Centers_Read_Logic = require("./code/cost-centers-read-logic");
const gl_Accounts_Read_Logic = require("./code/gl-accounts-read-logic");
const material_Groups_Read_Logic = require("./code/material-groups-read-logic");
const wbs_Elements_Read_Logic = require("./code/wbs-elements-read-logic");
const assign_Approvers_Logic = require("./code/assign-approvers-logic");
const {
  approveRequest,
  rejectRequest,
} = require("./code/approve-reject-request");
const requests_Resubmit_Logic = require("./code/requests-resubmit-logic");
const download_Approver_Matrix_Template_Logic = require("./code/download-approver-matrix-template-logic");
const upload_Approver_Matrix_Logic = require("./code/upload-approver-matrix-logic");
const download_GL_Grouping_Template_Logic = require("./code/download-gl-grouping-template-logic");
const upload_GL_Grouping_Logic = require("./code/upload-gl-grouping-logic");
const download_Department_Grouping_Template_Logic = require("./code/download-department-grouping-template-logic");
const upload_Department_Grouping_Logic = require("./code/upload-department-grouping-logic");
const download_Functional_Department_Grouping_Template_Logic = require("./code/download-functional-department-grouping-template-logic");
const upload_Functional_Department_Grouping_Logic = require("./code/upload-functional-department-grouping-logic");
const download_Building_Grouping_Template_Logic = require("./code/download-building-grouping-template-logic");
const upload_Building_Grouping_Logic = require("./code/upload-building-grouping-logic");
const download_Region_Branch_Grouping_Template_Logic = require("./code/download-region-branch-grouping-template-logic");
const upload_Region_Branch_Grouping_Logic = require("./code/upload-region-branch-grouping-logic");
const get_Approvers_Logic = require("./code/get-approvers-logic");
const get_Request_Approvers_Logic = require("./code/get-request-approvers-logic");
const delegate_Approval_Logic = require("./code/delegate-approval-logic");
const workflow_Logs_Read_Logic = require("./code/workflow-logs-read-logic");

class ZSVC_PPS_VIREMENT extends LCAPApplicationService {
  async init() {
    this.before("CREATE", "Requests", async (request) => {
      await requests_Before_Create_Logic(request);
    });

    this.before("CREATE", "Requests.drafts", async (request) => {
      await requests_Drafts_Before_Create_Logic(request);
    });

    this.before("CREATE", "RequestItems.drafts", async (request) => {
      await requestitems_Drafts_Before_Create_Logic(request);
    });

    this.before("UPDATE", "RequestItems.drafts", async (request) => {
      await requestitems_Drafts_Before_Update_Logic(request);
    });

    this.after("CREATE", "Requests", async (results, request) => {
      await requests_After_Create_Logic(results, request);
    });

    this.on("calculateValues", "Requests", async (request) => {
      return requests_CalculateValues_Logic(request);
    });

    this.on("calculateValues", "Requests.drafts", async (request) => {
      return requests_Drafts_CalculateValues_Logic(request);
    });

    /*
     * Both targets are needed: Fiori Elements reads the list through
     * the draft union (Requests.drafts) whenever its filter carries the
     * IsActiveEntity / SiblingEntity predicates, and through Requests
     * otherwise.
     */
    this.before("READ", "Requests", async (request) => {
      await requests_List_Scope_Logic(request);
    });

    this.before("READ", "Requests.drafts", async (request) => {
      await requests_List_Scope_Logic(request);
    });

    this.after("READ", "Requests", async (results, request) => {
      await requests_After_Read_Logic(results, request);
    });

    this.on("downloadItemsTemplate", async (request) => {
      return download_Items_Template_Logic(request);
    });

    this.on("uploadItems", "Requests.drafts", async (request) => {
      return requests_Drafts_Upload_Items_Logic(request);
    });

    this.before("DELETE", "RequestItems.drafts", async (request) => {
      await requestitems_Drafts_Before_Delete_Logic(request);
    });

    this.after("CREATE", "RequestItems.drafts", async (results, request) => {
      await requestitems_Drafts_After_Create_Logic(results, request);
    });

    this.after("UPDATE", "RequestItems.drafts", async (results, request) => {
      await requestitems_Drafts_After_Update_Logic(results, request);
    });

    this.after("UPDATE", "Requests.drafts", async (results, request) => {
      await requests_Drafts_After_Update_Logic(results, request);
    });

    this.before("UPDATE", "Requests", async (request) => {
      await requests_Before_Update_Logic(request);
    });

    this.after("READ", "Requests.drafts", async (results, request) => {
      await requests_Drafts_After_Read_Logic(results, request);
    });

    this.on("READ", "RecentRequests", async (request) => {
      return await recent_Requests_Read_Logic(request);
    });

    this.on("READ", "UserDetails", async (request) => {
      return await user_Details_Read_Logic(request);
    });

    this.on("READ", "PendingApprovalCount", async (request) => {
      return await pending_Approval_Count_Read_Logic(request);
    });

    this.on("READ", "CostCenters", async (request) => {
      return await cost_Centers_Read_Logic(request);
    });

    this.on("READ", "GLAccounts", async (request) => {
      return await gl_Accounts_Read_Logic(request);
    });

    this.on("READ", "MaterialGroups", async (request) => {
      return await material_Groups_Read_Logic(request);
    });

    this.on("READ", "WBSElements", async (request) => {
      return await wbs_Elements_Read_Logic(request);
    });

    this.on("assignApprovers", async (request) => {
      return assign_Approvers_Logic(request);
      // return approveRequest(request);
      // return rejectRequest(request);
    });

    this.on("downloadApproverMatrixTemplate", async (request) => {
      return download_Approver_Matrix_Template_Logic(request);
    });

    this.on("uploadApproverMatrix", async (request) => {
      return upload_Approver_Matrix_Logic(request);
    });

    this.on("downloadGLGroupingTemplate", async (request) => {
      return download_GL_Grouping_Template_Logic(request);
    });

    this.on("uploadGLGrouping", async (request) => {
      return upload_GL_Grouping_Logic(request);
    });

    this.on("downloadDepartmentGroupingTemplate", async (request) => {
      return download_Department_Grouping_Template_Logic(request);
    });

    this.on("uploadDepartmentGrouping", async (request) => {
      return upload_Department_Grouping_Logic(request);
    });

    this.on("downloadFunctionalDepartmentGroupingTemplate", async (request) => {
      return download_Functional_Department_Grouping_Template_Logic(request);
    });

    this.on("uploadFunctionalDepartmentGrouping", async (request) => {
      return upload_Functional_Department_Grouping_Logic(request);
    });

    this.on("downloadBuildingGroupingTemplate", async (request) => {
      return download_Building_Grouping_Template_Logic(request);
    });

    this.on("uploadBuildingGrouping", async (request) => {
      return upload_Building_Grouping_Logic(request);
    });

    this.on("downloadRegionBranchGroupingTemplate", async (request) => {
      return download_Region_Branch_Grouping_Template_Logic(request);
    });

    this.on("uploadRegionBranchGrouping", async (request) => {
      return upload_Region_Branch_Grouping_Logic(request);
    });

    this.on("getApprovers", async (request) => {
      return get_Approvers_Logic(request);
    });

    this.on("getRequestApprovers", async (request) => {
      return get_Request_Approvers_Logic(request);
    });

    this.on("READ", "WorkflowLogs", async (request) => {
      return workflow_Logs_Read_Logic(request);
    });

    this.on("approveRequest", "Requests", async (request) => {
      return approveRequest(request);
    });

    this.on("rejectRequest", "Requests", async (request) => {
      return rejectRequest(request);
    });

    this.on("delegateApproval", "Requests", async (request) => {
      return delegate_Approval_Logic(request);
    });

    this.on("resubmitRequest", "Requests", async (request) => {
      return requests_Resubmit_Logic(request);
    });

    return super.init();
  }
}

module.exports = {
  ZSVC_PPS_VIREMENT,
};
